
user www-data;

events {

}

http {
    include /etc/nginx/mime.types;

    error_log 	/dev/stderr;
	access_log	/dev/stdout;

    server {

        server_name alel-you;
        listen 443 ssl;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_certificate /etc/nginx/ssl/certs/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/private/inception.key;

        root /var/www/html;
        index   index.php;

        location ~ \.php$ {
            include snippets/fastcgi-php.conf;
            fastcgi_pass wordpress:9000;
        }
    }
}
